apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernetes-test
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: fastapi
          image: sepo96/kubernetes_test:fastapi
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: kubernetes-test
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi

